name: 'leancloud-waker'
on:
    schedule:
        # min, hour, day, month, week
        - cron: '0 13 * * *'
jobs:
    leancloud:
        runs-on: ubuntu-latest
        steps:
            - name: 'WakeUpLeanCloud'
              env:
                    ADMIN_URL: ${{ secrets.SITE }}
              run: date && curl --head -k $ADMIN_URL
